# Generated by Django 3.1.3 on 2020-11-03 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20201103_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userid',
            field=models.CharField(auto_created=True, max_length=100, unique=True),
        ),
    ]
