# Generated by Django 3.1.3 on 2020-11-03 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_auto_20201103_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, editable=False, max_length=100, unique=True),
        ),
    ]
