# Generated by Django 3.1.3 on 2020-11-03 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_auto_20201103_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('f', 'Faculty'), ('s', 'Student')], default='f', max_length=100),
        ),
    ]
