# Generated by Django 3.1.3 on 2020-11-03 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectID', models.CharField(blank=True, editable=False, max_length=100, unique=True)),
                ('subjectName', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='college',
            field=models.CharField(default='CPICA', editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='course',
            field=models.CharField(choices=[('MCA3663', 'MCA'), ('BCA9610', 'BCA'), ('BBA4615', 'BBA'), ('MBA8269', 'MBA')], max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('a', 'Admin'), ('f', 'Faculty'), ('s', 'Student')], default='s', max_length=100),
        ),
    ]
