# Generated by Django 3.1.3 on 2020-11-03 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_auto_20201103_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='course',
            field=models.CharField(choices=[('MCA3663', 'MCA'), ('BCA9610', 'BCA'), ('BBA4615', 'BBA'), ('MBA8269', 'MBA')], default=None, max_length=100),
        ),
    ]
