# Generated by Django 3.1.3 on 2020-11-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_auto_20201103_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectID', models.CharField(blank=True, editable=False, max_length=100, unique=True)),
                ('subjectName', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='faculty_subject',
            name='faculty',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
