# Generated by Django 3.1.3 on 2020-11-04 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0018_auto_20201104_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty_subject',
            name='semester',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default=1, max_length=100),
        ),
    ]
