# Generated by Django 3.1.3 on 2020-11-04 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0019_auto_20201104_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='parentid',
            field=models.CharField(blank=True, editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='faculty_subject',
            name='faculty',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
