# Generated by Django 3.1.3 on 2020-11-08 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0020_auto_20201105_0215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(choices=[('MCA3663', 'MCA'), ('BCA9610', 'BCA'), ('BBA4615', 'BBA'), ('MBA8269', 'MBA')], default=None, max_length=100)),
                ('semester', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default=1, max_length=100)),
                ('subjectName', models.CharField(choices=[('SUB8463', 'ML'), ('SUB3964', 'DAA'), ('SUB8301', 'Software Engineering'), ('SUB3177', 'Laravel'), ('SUB1669', 'test')], default=None, max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='faculty_subject',
            name='course',
            field=models.CharField(choices=[('MCA3663', 'MCA'), ('BCA9610', 'BCA'), ('BBA4615', 'BBA'), ('MBA8269', 'MBA')], default=None, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='faculty_subject',
            name='faculty',
            field=models.CharField(choices=[('USER18313', 'Test Faculty')], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='faculty_subject',
            name='subjectName',
            field=models.CharField(choices=[('SUB8463', 'ML'), ('SUB3964', 'DAA'), ('SUB8301', 'Software Engineering'), ('SUB3177', 'Laravel'), ('SUB1669', 'test')], default=None, max_length=100),
        ),
    ]
