# Generated by Django 3.1.3 on 2020-11-08 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0022_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback_reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionid', models.CharField(blank=True, max_length=10)),
                ('facultyid', models.CharField(max_length=10)),
                ('studentid', models.CharField(max_length=10)),
                ('subjectid', models.CharField(max_length=10)),
                ('courseid', models.CharField(max_length=10)),
                ('semester', models.CharField(max_length=10)),
                ('rating', models.CharField(blank=True, max_length=10)),
                ('totalrating', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='faculty_subject',
            name='faculty',
            field=models.CharField(choices=[('USER18313', 'Test Faculty'), ('USER32093', 'Hardik Soni')], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='enrollNo',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
