# Generated by Django 3.1.3 on 2020-11-08 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0024_auto_20201108_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback_reply',
            name='questionid',
        ),
        migrations.AddField(
            model_name='feedback_reply',
            name='qformid',
            field=models.CharField(blank=True, editable=False, max_length=10, unique=True),
        ),
    ]
