# Generated by Django 3.1.3 on 2020-11-15 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0025_auto_20201108_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback_reply',
            name='totalrating',
        ),
    ]
